---
title: "LengthOfLines"
author: "Mark Gallivan"
date: ""
output: 
  md_document:
    variant: markdown_github
---
## Set up
Purpose: Calculate the length of the lines within each polygon. Test if identical results are given by the use of the raster and sf package 

```{r setup}
rm(list = ls())

library(raster)
library(sp)
cds <- rbind(c(-125,0), c(0,60), c(40,5), c(15,-45))
lines <- spLines(cds, cds-20, cds+20, attr=data.frame(Lid=1:3))

p1 <- rbind(c(180,20), c(140,-55), c(10, 0), c(140,60), c(180,20))
p2 <- rbind(c(-10,0), c(-140,-60), c(-160,0), c(-140,55), c(-10,0))
pols <- spPolygons(p1, p2, attr=data.frame(Pid=1:2))

plot(pols)
lines(lines, col='blue')
```

## Solution using raster::intersection

```{r Solution}

## Example 1. Use raster::intersection

library(raster)
library(sp)
cds <- rbind(c(-125,0), c(0,60), c(40,5), c(15,-45))
lines <- spLines(cds, cds-20, cds+20, attr=data.frame(Lid=1:3))

p1 <- rbind(c(180,20), c(140,-55), c(10, 0), c(140,60), c(180,20))
p2 <- rbind(c(-10,0), c(-140,-60), c(-160,0), c(-140,55), c(-10,0))
pols <- spPolygons(p1, p2, attr=data.frame(Pid=1:2))

plot(pols)
lines(lines, col='blue')

x <- raster::intersect(lines, pols)
plot(x) # just show the lines contained in each polygon

p <- lapply(1:length(pols), function(i) x[x$Pid == i, ])

sp::SpatialLinesLengths(p[[2]])

lapply(p, function(x) sum(SpatialLinesLengths(x)))

```

## Solution using sf::intersection and comparison

```{r solution2}

# Example 2. Use of sf::intersection
library(sf)
str(lines)
lines <- sf::st_as_sf(lines)
pols <- sf::st_as_sf(pols)

x_sf <- sf::st_intersection(lines, pols)

p_sf <- lapply(1:length(pols), function(i) x_sf[x_sf$Pid == i, ])

lapply(p_sf, function(x) sum(st_length(x)))

## test if raster::intersection is equal to sf::st_intersection

if (identical(round(sum(unlist(lapply(p, function(x) sum(SpatialLinesLengths(x)))))), round(sum(unlist(lapply(p_sf, function(x) sum(st_length(x)))))))) {
  print("Yay! Results are the same")
} else {
  print("Oh no, raster::intersection and sf::st_intersection gave different results")
}

```
